### ISSUE TITLE
0.9.0-m1 release of subctl deploys devel images

### ISSUE THREAD

**Issue by nyechiel** [submariner-io/submariner-operator#1129]
**What happened**:

`subctl` 0.9.0-m1 deploys devel images

**What you expected to happen**:

0.8.1-style behavior, where `subctl` deploys the default version out-of-the-box (without needing to use the `--version` flag)

**Comment by nyechiel** [comment]
More info on this:

1. Download `subctl` 0.9.0-m1:

`curl -Ls https://get.submariner.io | VERSION=0.9.0-m1 bash`

2. Try to deploy Submariner via `subctl`

3. You end up with `devel` images

One way to workaround this is to explicitly set the `version` flag on `subctl join` commands, but it's really a bug.

**Comment by tpantelis** [comment]
By default, the image versions come from the `version` field of the `Submariner` resource (or `ServiceDiscovery` for LH images). `subctl join` creates the `Submariner` resource and sets the `Version` field via the `versions.DefaultSubmarinerOperatorVersion` constant by default. `versions.DefaultSubmarinerOperatorVersion` was hardcoded to "0.9.0-m1" during the last release process. However when building `subctl`, it is specifically calculated by the following in the Makefile:

`-X=github.com/submariner-io/submariner-operator/pkg/versions.DefaultSubmarinerOperatorVersion=$(if eq($(patsubst subctl-devel-%,devel,$(CALCULATED_VERSION)),devel),devel,$(CALCULATED_VERSION))" \`

This was recently changed by https://github.com/submariner-io/submariner-operator/pull/1067. I'm not really clear on the intention.  The CALCULATED_VERSION is set in shipyard by `$(shell git describe --tags --dirty="-$(DEV_VERSION)" --exclude="$(CUTTING_EDGE)" --exclude="latest")`.  Running it locally, it evaluates to `v0.9.0-m1-67-g8388f77-dev`. The `patsubst` part evaluates to $(CALCULATED_VERSION) unchanged as the pattern `subctl-devel-%` isn't present (I'm not sure under what case it would be present). So now the `if` reduces to:
 
  `$(if eq(v0.9.0-m1-67-g8388f77-dev,devel),devel,$(CALCULATED_VERSION))`

Logically, the `eq` conditional should clearly evaluate to false and the `if` should yield $(CALCULATED_VERSION) (ie `v0.9.0-m1-67-g8388f77-dev`) instead of `devel`. However it doesn't b/c, according to [this](https://www.gnu.org/software/make/manual/html_node/Conditional-Functions.html), the `if` condition is true if it expands to a non-empty string. But `eq` needs to be a var in order to be expanded, ie `$(eq(...,devel))`.

@skitt Can you verify if the `if` expression, specifically the `patsubst` part, is still valid?

**Comment by tpantelis** [comment]
We decided on a simpler approach:

https://github.com/submariner-io/submariner-operator/pull/1227
https://github.com/submariner-io/releases/pull/113
