### ISSUE TITLE
exitOnError prints %!(EXTRA string="the error...")

### ISSUE THREAD

**Issue by mangelajo** [submariner-io/submariner-operator#118]
$ ./bin/subctl deploy-broker
The provided kubeconfig is invalid%!(EXTRA string=stat clusterB/auth/kubeconfig: no such file or directory)

We should convert error to string with err.string() before printing it out.

**Comment by Jaanki** [comment]
%!(EXTRA string= is because of incorrect format of fmt (https://golang.org/pkg/fmt/). Adding %s removes it. 

exitOnError("Unable to determine the Kubernetes connection configuration: %s", err)

But the word 'stat' is present which I am guessing is part of err.

output:
Unable to determine the Kubernetes connection configuration: stat /path/to/kubeconfig: no such file or directory

This applies to all exitOnError functions.

I used exitOnError in  PR #127 with %s and am getting proper error message.

 ./bin/subctl join --kubeconfig ~/path/to/kubeconfig
Argument missing: broker-info.subm file generated by 'subctl deploy-broker' not passed

**Comment by mangelajo** [comment]
I think it was because we where trying to print "err" as %s, but now we do err.Error() I think, which converts to string.
