### ISSUE TITLE
subctl validate firewall metrics fails

### ISSUE THREAD

**Issue by SteveMattar** [submariner-io/submariner-operator#1285]
What happened:
When running `subctl validate firewall metrics` with SDN and without globalnet , it fails:

⢄⡱ Validating the firewall configuration to check if metrics port (8080) is allowed in cluster "api-smattar-cluster1-devcluster-openshift-com:6443" 
 ✓ Validating the firewall configuration to check if metrics port (8080) is allowed in cluster "api-smattar-cluster1-devcluster-openshift-com:6443"
 ✗ The tcpdump output from the sniffer pod does not contain the client pod HostIP. Please check that your firewall configuration allows TCP/8080 traffic on the "ip-10-0-86-173.ec2.internal" node.

What you expected to happen:
subctl validate should work

How to reproduce it (as minimally and precisely as possible):
Run `subctl validate firewall metrics`.

Anything else we need to know?:

Environment:

Submariner version (use subctl version): 0.9.0rc0
Kubernetes version (use kubectl version): Openshift 4.8
Cloud provider or hardware configuration: AWS
OS (e.g: cat /etc/os-release):
Kernel (e.g. uname -a):
Install tools:
Network plugin and version (if this is a network-related bug):
Others:

**Comment by nyechiel** [comment]
@SteveMattar I am not clear on what the actual issue is here. The output suggests that there is a real issue with the underlying firewall config - are you saying that this is not the case? i.e, it seems like the fact that `subctl validate` fails here is a symptom and we need to understand the root casue.

**Comment by sridhargaddam** [comment]
@SteveMattar As Nir mentioned, please check if TCP/8080 is allowed in firewall configuration. The other thing that we can also check is to retry the command increasing the validation timeout. Basically, as part of this validation, we spawn a pod on Gateway nodes and non-Gateway nodes. Let's try to rule-out that the issue is because of timing (On KIND setup, Pods get spawned quickly, but with other environments, it might take some additional time. If this is the case, we can increase the default timeout)

`subctl validate firewall metrics --validation-timeout 200`

**Comment by SteveMattar** [comment]
@sridhargaddam I will check that port but isn't this being done by our terraform scripts already?

**Comment by nyechiel** [comment]
> @sridhargaddam I will check that port but isn't this being done by our terraform scripts already?

Yes, should be. But maybe there is a bug in the script or you did something wrong. This is what we need to understand.

**Comment by SteveMattar** [comment]
I see this inbound rule in my security group
It is applied on the worker nodes only
![2021-04-22_13-28](https://user-images.githubusercontent.com/17129333/115699998-e8a83580-a36e-11eb-824b-8ddb809eeb38.png)

**Comment by SteveMattar** [comment]
@sridhargaddam it works if the gateway runs on a worker node but on the master nodes the inbound rule for port 8080 is not defined as part of the terraform script. In this case I need to open the ports manually.
I'm closing this issue, the functionality is working as expected.

**Comment by sridhargaddam** [comment]
@SteveMattar yes, currently the terraform scripts (aka prep_for_subm.sh) do not configure inbound rules for master nodes as we do not label the master nodes with Gateway label. I saw the slack conversation where it was mentioned that you tried this manually. So whatever the tool reported was valid :) Thanks for checking Steve.
