### ISSUE TITLE
subctl "clusterid" flag rename

### ISSUE THREAD

**Issue by manosnoam** [submariner-io/submariner-operator#229]
`--clusterid <what-so-ever>` flag is required when joining a new member of Submariner.
However, clusterid is not directly related to the kubernetes cluster itself, or the kubeconfig of this cluster.  It's a unique id, chosen by the user (not auto-generated), that is required by the submariner tunnel creation.

So, instead of calling this flag “--clusterid”, can we rename it to it “--tunnel-id”?

**Comment by mangelajo** [comment]
It's not a good idea.

Because a single cluster can have several tunnels. And we couldn't have the same tunnel-id for each tunnel to a cluster.

ClusterID is fine, because it's supposed to be an ID for the cluster.

We thought of automatically assigning an ID to the cluster, but then that's confusing when you try to debug. Because instead of looking for a human name you gave you find yourself looking for <uuid> like names.

**Comment by sridhargaddam** [comment]
@manosnoam shall we close this issue?
