### ISSUE TITLE
Lighthouse combinations don't test the dataplane

### ISSUE THREAD

**Issue by mangelajo** [submariner-io/submariner-operator#437]
We have an ongoing discussion about testing or not the the connectivity part for the lighthouse
patches.

Currently it's disabled at least until globalnet is stable again, to maintain an indicator of lighthouse health regardless of the globalnet status.

https://github.com/submariner-io/submariner-operator/blob/7e76168c122496b79afd77005bd647b86a005f15/scripts/kind-e2e/e2e.sh#L39

**Comment by mkolesnik** [comment]
I don't see this change as necessary or productive, since the "bare" lighthouse job is quite stable, and both globalnet (with or without lighthouse) are unstable, we won't gain anything by "masking" the globalnet+lighthouse jobs, we should instead focus on making globalnet (or tests of it) more stable.

**Comment by vthapar** [comment]
Note that it is not that we skip `connectivity` for lighthouse *patches*, we have separate jobs that run connectivity tests. Issue we're discussing is if we should skip testing `connectivity` when we're testing discovery or not. In CI, I think we definitely should coz it is already being tested in other jobs. 

Only issue was having an option with `make e2e` to run both or just `connectivity` Either can be made default as long as we add an option to run the other.

**Comment by mkolesnik** [comment]
> Note that it is not that we skip `connectivity` for lighthouse _patches_, we have separate jobs that run connectivity tests. Issue we're discussing is if we should skip testing `connectivity` when we're testing discovery or not. In CI, I think we definitely should coz it is already being tested in other jobs.
> 

I disagree with this point, if you have a failure due to connectivity issues but you dont test it (notice shipyard only does a very basic and limited connectivity test), and that issue also causes the lighthouse test to fail, then isolating the failure would be more difficult if you dont run the connectivity tests as well.
I.E. the more data points you have, the easier it'll be to understand what's causing the failure.
> Only issue was having an option with `make e2e` to run both or just `connectivity` Either can be made default as long as we add an option to run the other.

**Comment by vthapar** [comment]
> I disagree with this point, if you have a failure due to connectivity issues but you dont test it (notice shipyard only does a very basic and limited connectivity test), and that issue also causes the lighthouse test to fail, then isolating the failure would be more difficult if you dont run the connectivity tests as well.

Then you should be okay if connectivity failures can't cause Lighhouse to fail? Lighthouse E2E doesn't fail if connectivity fails. Lighthouse can work even if IPSec tunnels are down as long as control plane is up. There are no dataplane connectivity tests. Lighthouse E2E only uses dig. We already removed curl from Lighthouse e2e.

**Comment by mkolesnik** [comment]
As I mentioned on the slack channel, the operator is deploying an entire system, and it makes sense to test all that it deploys to make sure it all plays well together.
To test just individual components, you have the different e2e tests in each repo.

**Comment by mangelajo** [comment]
Yeah, I'm more in the line of ... let's test all we deploy  as a whole. If a test fails we have the logs to know if it's lighthouse or if it's globalnet or connectivity. 

Having a decent dashboard and log collection system is what we miss at this point.
