### ISSUE TITLE
Make the subctl boolean flags more consistent

### ISSUE THREAD

**Issue by skitt** [submariner-io/submariner-operator#649]
Currently `subctl` has the following flags, across all sub-commands:

* `--globalnet` (default `false`);
* `--service-discovery` (default `true` now);
* `--disable-nat` (default `false`; the flag is slightly inaccurate too, it should refer to NAT-T);
* `--ipsec-debug` (default `false`);
* `--subm-debug` (default `false`, deprecated in favour of `--enable-pod-debugging`);
* `--enable-pod-debugging` (default `false`);
* `--no-label` (default `false`);
* `--enable-disruptive` (default `false`);
* `--verbose` (default `false`).

It would be more consistent if we followed these rules:
* boolean flags should be “positive”, *i.e.* setting them should enable;
* `no` or `enable`/`disable` prefixes shouldn’t be hard-coded (I’m working on adding them to the flag library);
* we should rely on `=false` to disable features.

This would result in the following changes:
* `--disable-nat` becomes `--natt`, default `true` (the current flag is deprecated, equivalent to `--natt=false`);
* `--enable-pod-debugging` becomes `--pod-debug` to match the other debug flags, default `false` (the current flag is deprecated, equivaltn to `--pod-debug`);
* `--no-label` becomes `--label-gateway`, default `true` (the current flag is deprecated, equivalent to `--label-gateway=false`);
* `--enable-disruptive` becomes `--disruptive-tests`, default `false`) (the current flag is deprecated, equivalent to `--enable-disruptive`).

**Comment by skitt** [comment]
@manosnoam I’d appreciate your feedback on this one!

**Comment by mangelajo** [comment]
Makes sense, coherence always helps.

**Comment by manosnoam** [comment]
Thanks for asking @skitt 
Since I did not use all flags in my tests yet, can you update the descriptions with sections above related flags: 

- Flags for any subctl command
 ...
- Flags for deploy command
 ...
- Flags for join command
 ...

Regarding --ipsec-debug, is it like --enable-pod-debugging, or more like --verbose ?
In general, having few **flags for verbosity/debug**, is somewhat confusing. 
Can you have these flags with same naming convention ?

Regarding "--disable-option" (in conjunction with "--enable-option") flags, it seems better than "**--no**-option" flags.

We might even consider having just "disable" flags, and remove "enable", as it is obvious that --option defaults to option=true.
For example, change `--enable-pod-debugging` to `--pod-debugging`. 
(I know that I suggested "--enable-pod-debugging" previously, but now that we consider renaming flags, it might be better)

**Comment by skitt** [comment]
I’m still planning to address this at some point (before 1.0).

**Comment by skitt** [comment]
OK, how does the stale bot measure activity? Only comments?
